AWSTemplateFormatVersion: '2010-09-09'
Description: Quantifex Frontend - S3 + CloudFront for React SPA

Parameters:
  BackendApiUrl:
    Type: String
    Description: Backend API URL (e.g., https://api.example.com/api)
    Default: ''

Resources:
  # S3 Bucket for Frontend Static Files
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub quantifex-frontend-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Project
          Value: Quantifex

  # S3 Bucket Policy for Public Read Access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  # CloudFront Origin Access Identity (for alternative private setup)
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub Access identity for ${FrontendBucket}

  # CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Comment: Quantifex Frontend Distribution
      Tags:
        - Key: Project
          Value: Quantifex

Outputs:
  BucketName:
    Description: S3 bucket name for frontend files
    Value: !Ref FrontendBucket
    Export:
      Name: QuantifexFrontendBucket
  
  BucketWebsiteURL:
    Description: S3 website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
    Export:
      Name: QuantifexFrontendBucketUrl
  
  CloudFrontURL:
    Description: CloudFront distribution URL
    Value: !GetAtt FrontendDistribution.DomainName
    Export:
      Name: QuantifexFrontendCloudfrontUrl
  
  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref FrontendDistribution
    Export:
      Name: QuantifexFrontendDistributionId
  
  BackendApiUrl:
    Description: Backend API URL (for reference)
    Value: !Ref BackendApiUrl
